import { defineField } from "sanity";
import { EN_FIELDSET } from "./helpers";

function paren(name: string, title: string) {
  return [
    defineField({ name, title, type: "string" }),
    defineField({ name: `${name}En`, title: `${title} (EN)`, type: "string", fieldset: "en" }),
  ];
}

function groep(name: string, title: string, description: string, items: [string, string][]) {
  return defineField({
    name,
    title,
    type: "object",
    description,
    options: { collapsible: true, collapsed: false },
    fieldsets: [EN_FIELDSET],
    fields: items.flatMap(([key, label]) => paren(key, label)),
  });
}

/** Visitor-facing words. Which links and fields exist stays in the code. */
export const labelsField = defineField({
  name: "labels",
  title: "Knoppen en labels",
  type: "object",
  group: "labels",
  description: "De woorden op knoppen, in het menu en in de footer. Welke links er zijn, verandert hier niet. Een leeg veld toont de zin die er nu staat.",
  options: { collapsible: false },
  fields: [
    groep("menu", "Menu", "De woorden in het menu. De links zelf blijven zoals ze zijn.", [
      ["aanbod", "Aanbod"],
      ["kinesitherapie", "Kinesitherapie"],
      ["performance", "Performance"],
      ["train", "Train"],
      ["training", "Training"],
      ["test", "Test en analyse"],
      ["revalidatie", "Revalidatie"],
      ["gx", "GX"],
      ["b2b", "B2B"],
      ["olympia", "Olympia"],
      ["kineAbonnement", "Kiné-abonnement"],
      ["overLocatie", "Over deze locatie"],
      ["sportkine", "Sportkinesitherapie"],
      ["personalTraining", "Personal Training"],
      ["performanceCoaching", "Performance Coaching"],
      ["highPerformance", "High Performance Coaching"],
      ["duoTraining", "Duo Training"],
      ["boxing", "Boxing 1-on-1"],
      ["performanceScreening", "Performance Screening"],
      ["loopanalyse", "Loopanalyse met OnTracx"],
      ["vald", "VALD Screening"],
      ["corporate", "Corporate Coaching"],
      ["trainingWerk", "Training op het werk"],
      ["lessenrooster", "Lessenrooster"],
      ["team", "Team"],
      ["overOns", "Over ons"],
      ["onsVerhaal", "Ons verhaal"],
      ["onzeVisie", "Onze visie"],
      ["events", "Events"],
      ["prijzen", "Prijzen"],
      ["faq", "FAQ"],
      ["vacatures", "Vacatures"],
      ["contact", "Contact"],
      ["afspraak", "Afspraak"],
      ["alleBehandelingen", "Alle behandelingen"],
      ["alleTrainingen", "Alle trainingen"],
      ["alleTraining", "Alle training"],
      ["blog", "Blog"],
      ["veelgesteldeVragen", "Veelgestelde vragen"],
      ["groepslessen", "Groepslessen"],
      ["visie", "Visie"],
      ["overMpc", "Over MPC"],
      ["sportrevalidatie", "Sportrevalidatie"],
      ["alleSportrevalidatie", "Alle sportrevalidatie"],
      ["lesroosterAlle", "Lesrooster & alle lessen"],
    ]),
    groep("footer", "Footer", "De woorden onderaan de pagina.", [
      ["aanbod", "Aanbod"],
      ["onsVerhaal", "Ons verhaal"],
      ["onzeVisie", "Onze visie"],
      ["prijzen", "Prijzen"],
      ["faq", "FAQ"],
      ["team", "Team"],
      ["blog", "Blog"],
      ["insights", "Insights/Blog"],
      ["vacatures", "Vacatures"],
      ["contact", "Contact"],
      ["groepslessen", "Groepslessen"],
      ["visie", "Visie"],
      ["openingsuren", "Openingsuren"],
      ["volgOns", "Volg ons"],
      ["route", "Routebeschrijving"],
      ["btw", "BTW"],
      ["privacy", "Privacy"],
      ["cookies", "Cookievoorkeuren"],
      ["voorwaarden", "Algemene voorwaarden"],
      ["onderdeel", "Onderdeel van Movenda"],
    ]),
    groep("formulier", "Formulieren", "Gedeelde woorden voor contact, welkom en groepslessen. De zinnen die bij één formulier horen, staan op die pagina.", [
      ["naam", "Naam"],
      ["email", "E-mail"],
      ["telefoon", "Telefoon"],
      ["ja", "Ja"],
      ["nee", "Nee"],
      ["nvt", "Niet van toepassing"],
    ]),
    groep("cookies", "Cookiebalk", "De balk onderaan, de eerste keer dat iemand de site bezoekt.", [
      ["titel", "Cookievoorkeuren"],
      ["tekst", "Uitleg"],
      ["privacy", "Privacy"],
      ["accepteren", "Oké"],
      ["weigeren", "Liever niet"],
    ]),
    groep("locatie", "Locatiepagina", "Korte koppen op beide locatiepagina’s: adres, uren, route, team.", [
      ["adres", "Adres"],
      ["maps", "Bekijk op Google Maps"],
      ["contact", "Contact"],
      ["openingsuren", "Openingsuren"],
      ["route", "Route"],
      ["btw", "BTW"],
      ["team", "Team op deze locatie"],
    ]),
  ],
});
