import { DocumentTextIcon } from "@sanity/icons";
import { defineField, defineType, type ConditionalPropertyCallbackContext } from "sanity";
import { EN_FIELDSET } from "./helpers";
import { maxItems, maxTekens, verplicht, GOOGLE_OMSCHRIJVING, googleTitel } from "./regels";

// Copy of the fixed pages (home, over, kine, …). One document per page, fixed
// `key`, never created or deleted from the Studio. Julie edits the H1, intro,
// hero photo, SEO and the text blocks that used to be hardcoded in Astro.
// Layout stays in code; which blocks a page shows follows from its key.

export const PAGINAS = [
  { key: "home", title: "Homepage", path: "/" },
  { key: "over", title: "Ons verhaal", path: "/over-ons/ons-verhaal" },
  { key: "onze-visie", title: "Onze visie", path: "/over-ons/onze-visie" },
  { key: "kinesitherapie", title: "Kinesitherapie (overzicht)", path: "/kinesitherapie" },
  { key: "training", title: "Training (overzicht)", path: "/training" },
  { key: "performance", title: "Performance (overzicht)", path: "/performance" },
  { key: "b2b", title: "B2B (overzicht)", path: "/b2b" },
  { key: "mpc", title: "MPC (overzicht)", path: "/mpc" },
  { key: "mpc-visie", title: "MPC — Visie", path: "/mpc/visie" },
  { key: "contact", title: "Contact", path: "/contact" },
  { key: "jobs", title: "Vacatures", path: "/jobs" },
  { key: "team", title: "Team", path: "/team" },
  { key: "groepslessen", title: "Groepslessen (GX)", path: "/groepslessen" },
  { key: "kine-abonnement", title: "Kiné-abonnement", path: "/kine-abonnement" },
  { key: "prijzen", title: "Prijzen", path: "/prijzen" },
  { key: "faq", title: "FAQ", path: "/faq" },
  { key: "blog", title: "Blog (overzicht)", path: "/blog" },
  { key: "events", title: "Events (overzicht)", path: "/events" },
  { key: "welkom", title: "Welkom (QR-formulier)", path: "/welkom" },
  { key: "privacy", title: "Privacy", path: "/privacy" },
  { key: "voorwaarden", title: "Algemene voorwaarden", path: "/voorwaarden" },
] as const;

export type PaginaKey = (typeof PAGINAS)[number]["key"];

// Field only shown on the listed pages.
const only =
  (...keys: PaginaKey[]) =>
  ({ document }: ConditionalPropertyCallbackContext) =>
    !keys.includes(((document as { key?: string } | undefined)?.key || "") as PaginaKey);

const ONDERTITEL: PaginaKey[] = ["home", "kinesitherapie", "performance", "b2b", "groepslessen", "kine-abonnement", "blog", "voorwaarden"];

const cookieRij = {
  type: "object",
  name: "cookieRij",
  fieldsets: [EN_FIELDSET],
  fields: [
    defineField({ name: "naam", title: "Naam", type: "string", validation: verplicht }),
    defineField({ name: "doel", title: "Doel (NL)", type: "text", rows: 2, validation: verplicht }),
    defineField({ name: "doelEn", title: "Doel (EN)", type: "text", rows: 2, fieldset: "en" }),
    defineField({ name: "termijn", title: "Hoelang (NL)", type: "string", validation: verplicht }),
    defineField({ name: "termijnEn", title: "Hoelang (EN)", type: "string", fieldset: "en" }),
    defineField({ name: "toestemming", title: "Toestemming (NL)", type: "string" }),
    defineField({ name: "toestemmingEn", title: "Toestemming (EN)", type: "string", fieldset: "en" }),
    defineField({
      name: "tool",
      title: "Verdwijnt als deze tool uit staat",
      type: "string",
      initialValue: "altijd",
      options: {
        list: [
          { title: "Altijd tonen", value: "altijd" },
          { title: "Google Analytics", value: "ga4" },
          { title: "Umami", value: "umami" },
          { title: "Instagram-feed", value: "instagram" },
          { title: "Google Reviews", value: "googleReviews" },
          { title: "Google Maps (altijd, laadt pas na een klik)", value: "maps" },
        ],
      },
    }),
    defineField({
      name: "dienstverlener",
      title: "Ook vermelden bij dienstverleners (NL)",
      type: "string",
      description: "Leeg = alleen in de tabel. Ingevuld = extra regel onder Dienstverleners, zolang de tool aan staat.",
    }),
    defineField({ name: "dienstverlenerEn", title: "Ook vermelden bij dienstverleners (EN)", type: "string", fieldset: "en" }),
  ],
  preview: { select: { title: "naam", subtitle: "termijn" } },
} as const;

const onlyKey =
  (key: PaginaKey) =>
  ({ document }: ConditionalPropertyCallbackContext) =>
    (document as { key?: string } | undefined)?.key !== key;

// NL field + its EN twin, only on the listed pages.
const tekstVeld = (name: string, title: string, keys: PaginaKey[], kort = false) =>
  kort
    ? [
        defineField({ name, title: `${title} (NL)`, type: "string", group: "blokken", hidden: only(...keys) }),
        defineField({ name: `${name}En`, title: `${title} (EN)`, type: "string", group: "blokken", fieldset: "en", hidden: only(...keys) }),
      ]
    : [
        defineField({ name, title: `${title} (NL)`, type: "text", rows: 3, group: "blokken", hidden: only(...keys) }),
        defineField({ name: `${name}En`, title: `${title} (EN)`, type: "text", rows: 3, group: "blokken", fieldset: "en", hidden: only(...keys) }),
      ];

const blok = {
  type: "object",
  name: "blok",
  fields: [
    defineField({ name: "kop", title: "Kop (NL)", type: "string", validation: verplicht }),
    defineField({ name: "tekst", title: "Tekst (NL)", type: "text", rows: 4, validation: verplicht }),
    defineField({ name: "kopEn", title: "Kop (EN)", type: "string" }),
    defineField({ name: "tekstEn", title: "Tekst (EN)", type: "text", rows: 4 }),
  ],
  preview: {
    select: { title: "kop", subtitle: "tekst" },
  },
} as const;

export default defineType({
  name: "pagina",
  title: "Pagina",
  type: "document",
  icon: DocumentTextIcon,
  description:
    "Titel, intro, foto en vaste teksten van deze pagina. De lijstjes (diensten, team, prijzen…) komen uit hun eigen records.",
  groups: [
    { name: "inhoud", title: "Tekst & foto", default: true },
    { name: "blokken", title: "Blokken" },
    { name: "seo", title: "SEO" },
  ],
  fieldsets: [
    EN_FIELDSET,
    {
      name: "homeKaarten",
      title: "Kaarten onderaan de homepage",
      description:
        "De twee kaarten onder de drie blokken. Die blokken, de slogan en de overige homepage-teksten staan in Site-instellingen, tabblad Homepage.",
      options: { collapsible: true, collapsed: false },
      hidden: only("home"),
    },
    {
      name: "homeTeam",
      title: "Teamblok onderaan de homepage",
      description: "In de tekst mag {aantal} staan. Dat wordt het aantal teamleden.",
      options: { collapsible: true, collapsed: false },
      hidden: only("home"),
    },
    {
      name: "homeKnoppen",
      title: "Knoppen bij de vestigingen",
      options: { collapsible: true, collapsed: false },
      hidden: only("home"),
    },
  ],
  fields: [
    defineField({
      name: "key",
      title: "Pagina",
      type: "string",
      readOnly: true,
      group: "inhoud",
      options: { list: PAGINAS.map((p) => ({ title: p.title, value: p.key })) },
      validation: verplicht,
    }),
    defineField({
      name: "ondertitel",
      title: "Kleine regel boven de titel (NL)",
      type: "string",
      group: "inhoud",
      hidden: only(...ONDERTITEL),
      description: "Bv. 'Kinesitherapie en personal training in Hasselt'.",
    }),
    defineField({ name: "ondertitelEn", title: "Kleine regel boven de titel (EN)", type: "string", group: "inhoud", fieldset: "en", hidden: only(...ONDERTITEL) }),
    defineField({ name: "titel", title: "Titel (H1, NL)", type: "string", group: "inhoud", validation: verplicht }),
    defineField({ name: "titelEn", title: "Titel (H1, EN)", type: "string", group: "inhoud", fieldset: "en" }),
    defineField({
      name: "slogan",
      title: "Slogan onder de titel (NL)",
      type: "string",
      group: "inhoud",
      hidden: only("groepslessen", "welkom"),
    }),
    defineField({ name: "sloganEn", title: "Slogan onder de titel (EN)", type: "string", group: "inhoud", fieldset: "en", hidden: only("groepslessen", "welkom") }),
    defineField({
      name: "intro",
      title: "Introtekst (NL)",
      type: "text",
      rows: 8,
      group: "inhoud",
      description:
        "Een lege regel = nieuwe alinea. Link: [tekst](https://…). Automatisch ingevuld: {kinesisten} en {trainers} (homepage), {aantal} (team), {basishonorarium} (prijzen), {email} (FAQ), {telefoon} (welkom).",
    }),
    defineField({ name: "introEn", title: "Introtekst (EN)", type: "text", rows: 8, group: "inhoud", fieldset: "en" }),
    defineField({
      name: "foto",
      title: "Hoofdfoto",
      type: "image",
      group: "inhoud",
      options: { hotspot: true },
      hidden: only("home", "over", "onze-visie", "kinesitherapie", "performance", "b2b", "groepslessen", "training", "mpc"),
      description: "Grote foto bovenaan. Leeg = de huidige foto van de site blijft staan. Kies een focuspunt op de persoon.",
    }),
    defineField({
      name: "fotoAlt",
      title: "Beschrijving van de foto (voor schermlezers en Google)",
      type: "string",
      group: "inhoud",
      hidden: only("home", "over", "onze-visie", "kinesitherapie", "performance", "b2b", "groepslessen", "training", "mpc"),
    }),
    defineField({
      name: "heroVideo",
      title: "Video bovenaan (in plaats van de foto)",
      type: "file",
      group: "inhoud",
      hidden: only("mpc"),
      options: { accept: "video/mp4,video/webm" },
      description:
        "Korte sfeervideo die geluidloos in een lus speelt op de plek van de hoofdfoto. Richtlijn: 10 à 20 seconden, liggend (16:9 of 4:3), maximaal 8 MB, geen geluid nodig. De hoofdfoto blijft het stilstaande beeld tot de video geladen is en voor bezoekers die bewegend beeld uitschakelen. Leeg = alleen de foto.",
    }),
    defineField({
      name: "fotoSecundair",
      title: "Tweede foto (verder op de pagina)",
      type: "cmsFoto",
      group: "inhoud",
      hidden: only("kinesitherapie", "training", "mpc"),
      description: "De foto naast de lijst met behandelingen of trainingen. Leeg = de huidige foto van de site blijft staan.",
    }),
    defineField({
      name: "bannerFoto",
      title: "Foto achter de slogan-banner",
      type: "cmsFoto",
      group: "inhoud",
      hidden: only("home"),
      description:
        "Brede sfeerfoto achter de slogan (‘Life has its ups and downs…’), tussen de partnerbalk en de drie pijlers. Kies een liggende foto en een focuspunt; er komt een donkerblauwe waas over. Leeg = de huidige foto blijft staan.",
    }),
    defineField({
      name: "olympiaKaartTitel",
      title: "Hasselt — titel",
      type: "string",
      group: "inhoud",
      fieldset: "homeKaarten",
      hidden: only("home"),
    }),
    defineField({
      name: "olympiaKaartTekst",
      title: "Hasselt — tekst",
      type: "text",
      rows: 3,
      group: "inhoud",
      fieldset: "homeKaarten",
      hidden: only("home"),
    }),
    defineField({
      name: "olympiaKaartCta",
      title: "Hasselt — knop",
      type: "string",
      group: "inhoud",
      fieldset: "homeKaarten",
      hidden: only("home"),
    }),
    defineField({
      name: "mpcKaartTitel",
      title: "Performance Centre — titel",
      type: "string",
      group: "inhoud",
      fieldset: "homeKaarten",
      hidden: only("home"),
    }),
    defineField({
      name: "mpcKaartTekst",
      title: "Performance Centre — tekst",
      type: "text",
      rows: 3,
      group: "inhoud",
      fieldset: "homeKaarten",
      hidden: only("home"),
    }),
    defineField({
      name: "mpcKaartCta",
      title: "Performance Centre — knop",
      type: "string",
      group: "inhoud",
      fieldset: "homeKaarten",
      hidden: only("home"),
    }),
    defineField({
      name: "teamBlokTitel",
      title: "Titel",
      type: "string",
      group: "inhoud",
      fieldset: "homeTeam",
      hidden: only("home"),
    }),
    defineField({
      name: "teamBlokTekst",
      title: "Tekst",
      type: "text",
      rows: 3,
      group: "inhoud",
      fieldset: "homeTeam",
      hidden: only("home"),
      description: "{aantal} wordt het aantal teamleden.",
    }),
    defineField({
      name: "teamBlokCta",
      title: "Knop",
      type: "string",
      group: "inhoud",
      fieldset: "homeTeam",
      hidden: only("home"),
    }),
    defineField({ name: "olympiaKaartTitelEn", title: "Hasselt — titel (EN)", type: "string", group: "inhoud", fieldset: "en", hidden: only("home") }),
    defineField({ name: "olympiaKaartTekstEn", title: "Hasselt — tekst (EN)", type: "text", rows: 3, group: "inhoud", fieldset: "en", hidden: only("home") }),
    defineField({ name: "olympiaKaartCtaEn", title: "Hasselt — knop (EN)", type: "string", group: "inhoud", fieldset: "en", hidden: only("home") }),
    defineField({ name: "mpcKaartTitelEn", title: "Performance Centre — titel (EN)", type: "string", group: "inhoud", fieldset: "en", hidden: only("home") }),
    defineField({ name: "mpcKaartTekstEn", title: "Performance Centre — tekst (EN)", type: "text", rows: 3, group: "inhoud", fieldset: "en", hidden: only("home") }),
    defineField({ name: "mpcKaartCtaEn", title: "Performance Centre — knop (EN)", type: "string", group: "inhoud", fieldset: "en", hidden: only("home") }),
    defineField({ name: "teamBlokTitelEn", title: "Teamblok — titel (EN)", type: "string", group: "inhoud", fieldset: "en", hidden: only("home") }),
    defineField({ name: "teamBlokTekstEn", title: "Teamblok — tekst (EN)", type: "text", rows: 3, group: "inhoud", fieldset: "en", hidden: only("home") }),
    defineField({ name: "teamBlokCtaEn", title: "Teamblok — knop (EN)", type: "string", group: "inhoud", fieldset: "en", hidden: only("home") }),
    defineField({ name: "belLabel", title: "Knop “Bel” (NL)", type: "string", group: "inhoud", fieldset: "homeKnoppen", hidden: only("home") }),
    defineField({ name: "contactLabel", title: "Knop “Contacteer ons” (NL)", type: "string", group: "inhoud", fieldset: "homeKnoppen", hidden: only("home") }),
    defineField({ name: "belLabelEn", title: "Knop “Bel” (EN)", type: "string", group: "inhoud", fieldset: "en", hidden: only("home") }),
    defineField({ name: "contactLabelEn", title: "Knop “Contacteer ons” (EN)", type: "string", group: "inhoud", fieldset: "en", hidden: only("home") }),
    defineField({
      name: "knopLabel",
      title: "Knop onder de intro (NL)",
      type: "string",
      group: "inhoud",
      hidden: only("kinesitherapie", "performance", "b2b"),
      description: "Bv. ‘Plan je afspraak’. Leeg = de huidige tekst.",
    }),
    defineField({ name: "knopLabelEn", title: "Knop onder de intro (EN)", type: "string", group: "inhoud", fieldset: "en", hidden: only("kinesitherapie", "performance", "b2b") }),
    defineField({
      name: "knopUrl",
      title: "Link van die knop",
      type: "string",
      group: "inhoud",
      hidden: only("kinesitherapie", "performance", "b2b"),
      description: "Bv. /team#keuzehulp of /contact?behandeling=B2B. De Engelse pagina krijgt automatisch /en ervoor. Leeg = de huidige link.",
    }),
    defineField({
      name: "aanbodTitel",
      title: "Kop boven de aanbodlijst (NL)",
      type: "string",
      group: "inhoud",
      hidden: only("kinesitherapie", "performance", "b2b"),
      description: "Leeg = ‘Aanbod’. De lijst zelf komt uit de diensten (aan/uit via ‘Toon in menu’).",
    }),
    defineField({ name: "aanbodTitelEn", title: "Kop boven de aanbodlijst (EN)", type: "string", group: "inhoud", fieldset: "en", hidden: only("kinesitherapie", "performance", "b2b") }),

    // --- Blocks per page -------------------------------------------------
    defineField({
      name: "blokken",
      title: "Tekstblokken onder de intro",
      type: "array",
      of: [blok],
      group: "blokken",
      hidden: only("over", "onze-visie", "kinesitherapie", "performance", "b2b", "groepslessen", "privacy", "voorwaarden"),
      description: "Kop en tekst. Een regel die begint met '- ' wordt een opsomming.",
    }),
    defineField({
      name: "kenmerken",
      title: "Principes (maximaal zes kaartjes)",
      type: "array",
      of: [blok],
      group: "blokken",
      hidden: only("onze-visie"),
      validation: maxItems(6),
    }),
    defineField({
      name: "stappenTitel",
      title: "Titel boven de stappen (NL)",
      type: "string",
      group: "blokken",
      hidden: true,
    }),
    defineField({ name: "stappenTitelEn", title: "Titel boven de stappen (EN)", type: "string", group: "blokken", fieldset: "en", hidden: true }),
    defineField({ name: "stappenIntro", title: "Tekst boven de stappen (NL)", type: "text", rows: 3, group: "blokken", hidden: true }),
    defineField({ name: "stappenIntroEn", title: "Tekst boven de stappen (EN)", type: "text", rows: 3, group: "blokken", fieldset: "en", hidden: true }),
    defineField({
      name: "stappen",
      title: "Stappen van een eerste bezoek",
      type: "array",
      of: [blok],
      group: "blokken",
      hidden: true,
      description: "De nummering komt automatisch.",
    }),
    defineField({
      name: "pijlers",
      title: "Drie pijlers (Training, Sportrevalidatie, Groepslessen)",
      type: "array",
      of: [blok],
      group: "blokken",
      hidden: only("mpc"),
      validation: maxItems(3),
      description: "Alleen de titel en de korte tekst. De foto's en links komen automatisch uit de diensten.",
    }),
    defineField({
      name: "verwijsopties",
      title: "Contactformulier — ‘Hoe ben je bij ons terechtgekomen?’",
      type: "array",
      group: "blokken",
      hidden: only("contact"),
      description:
        "De keuzes in het contactformulier, in deze volgorde. Per keuze kies je of er een vervolgvraag komt (naam van de verwijzer, naam van de club, welk event, of een vrij tekstvak). Leeg = de standaardlijst van de oude website.",
      of: [
        {
          type: "object",
          name: "verwijsoptie",
          fields: [
            defineField({ name: "label", title: "Keuze (NL)", type: "string", validation: verplicht }),
            defineField({ name: "labelEn", title: "Keuze (EN)", type: "string" }),
            defineField({
              name: "vervolg",
              title: "Vervolgvraag",
              type: "string",
              initialValue: "geen",
              options: {
                list: [
                  { title: "Geen", value: "geen" },
                  { title: "Naam van de verwijzer (arts, specialist…)", value: "naam" },
                  { title: "Naam van de club", value: "club" },
                  { title: "Welk event of welke activiteit?", value: "event" },
                  { title: "Vrij tekstvak (extra info)", value: "tekst" },
                ],
                layout: "radio",
              },
            }),
          ],
          preview: {
            select: { title: "label", vervolg: "vervolg" },
            prepare({ title, vervolg }) {
              const labels: Record<string, string> = { naam: "→ naam", club: "→ club", event: "→ event", tekst: "→ tekst" };
              return { title, subtitle: labels[vervolg as string] || "" };
            },
          },
        },
      ],
    }),
    defineField({
      name: "legeTekst",
      title: "Tekst als de lijst leeg is (NL)",
      type: "text",
      rows: 3,
      group: "blokken",
      hidden: only("jobs", "blog", "events"),
      description: "Verschijnt als er geen vacatures, blogposts of events zijn. Bij vacatures wordt de eerste regel vet en komt het e-mailadres automatisch uit Site-instellingen.",
    }),
    defineField({ name: "legeTekstEn", title: "Tekst als de lijst leeg is (EN)", type: "text", rows: 3, group: "blokken", fieldset: "en", hidden: only("jobs", "blog", "events") }),
    ...tekstVeld("afsluiter", "Afsluitende zin onderaan", ["over", "onze-visie"], true),
    ...tekstVeld("extraTekst", "Tekst onder de blokken", ["groepslessen"]),
    ...tekstVeld("prijsNotitie", "Tekst bij de prijzen", ["groepslessen"]),
    ...tekstVeld("formulierIntro", "Tekst boven het inschrijfformulier", ["groepslessen"]),
    ...tekstVeld("terugbetalingTitel", "Terugbetaling — titel", ["prijzen"], true),
    ...tekstVeld("terugbetalingTekst", "Terugbetaling — uitleg", ["prijzen"]),
    ...tekstVeld("perTherapeutTitel", "Tarieven per therapeut of coach — titel", ["prijzen"], true),
    ...tekstVeld("perTherapeutTekst", "Tarieven per therapeut — uitleg", ["prijzen"]),
    defineField({
      name: "bijgewerkt",
      title: "Datumregel (NL)",
      type: "string",
      group: "blokken",
      hidden: only("privacy"),
      description: "Bv. Laatst bijgewerkt: 11 september 2026.",
    }),
    defineField({ name: "bijgewerktEn", title: "Datumregel (EN)", type: "string", group: "blokken", fieldset: "en", hidden: only("privacy") }),
    defineField({ name: "cookiesKolomNaam", title: "Cookietabel — kolom “Wat” (NL)", type: "string", group: "blokken", hidden: only("privacy") }),
    defineField({ name: "cookiesKolomDoel", title: "Cookietabel — kolom “Doel” (NL)", type: "string", group: "blokken", hidden: only("privacy") }),
    defineField({ name: "cookiesKolomTermijn", title: "Cookietabel — kolom “Hoelang” (NL)", type: "string", group: "blokken", hidden: only("privacy") }),
    defineField({ name: "cookiesKolomToestemming", title: "Cookietabel — kolom “Toestemming” (NL)", type: "string", group: "blokken", hidden: only("privacy") }),
    defineField({ name: "cookiesKolomNaamEn", title: "Cookietabel — kolom “Wat” (EN)", type: "string", group: "blokken", fieldset: "en", hidden: only("privacy") }),
    defineField({ name: "cookiesKolomDoelEn", title: "Cookietabel — kolom “Doel” (EN)", type: "string", group: "blokken", fieldset: "en", hidden: only("privacy") }),
    defineField({ name: "cookiesKolomTermijnEn", title: "Cookietabel — kolom “Hoelang” (EN)", type: "string", group: "blokken", fieldset: "en", hidden: only("privacy") }),
    defineField({ name: "cookiesKolomToestemmingEn", title: "Cookietabel — kolom “Toestemming” (EN)", type: "string", group: "blokken", fieldset: "en", hidden: only("privacy") }),
    defineField({
      name: "cookies",
      title: "Cookietabel",
      type: "array",
      of: [cookieRij],
      group: "blokken",
      hidden: only("privacy"),
      description:
        "Zet in een tekstblok {cookies} waar de tabel moet komen, en {locaties} waar de twee vestigingen moeten komen. Een tool die onder Site-instellingen → Analytics uit staat, verdwijnt uit de tabel.",
    }),
    ...tekstVeld("wieTitel", "Kop boven de vestigingen", ["voorwaarden"], true),
    ...tekstVeld("annulatieTitel", "Kop boven het annulatiebeleid", ["voorwaarden"], true),
    ...tekstVeld("privacyZin", "Zin met link naar privacy", ["voorwaarden"]),
    defineField({
      name: "formulier",
      title: "Teksten van het formulier op deze pagina",
      type: "object",
      group: "blokken",
      hidden: only("contact", "welkom", "groepslessen"),
      description: "Alleen de zinnen die bij dit formulier horen. Naam, e-mail en de gedeelde knoppen staan bij Site-instellingen → Knoppen en labels.",
      options: { collapsible: true, collapsed: false },
      fieldsets: [EN_FIELDSET],
      fields: [
        defineField({ name: "welke", title: "Voor welke vestiging? (NL)", type: "string", hidden: onlyKey("contact") }),
        defineField({ name: "reden", title: "Waarvoor wil je langskomen? (NL)", type: "string", hidden: onlyKey("contact") }),
        defineField({ name: "kine", title: "Kinesitherapie (NL)", type: "string", hidden: onlyKey("contact") }),
        defineField({ name: "training", title: "Personal training (NL)", type: "string", hidden: onlyKey("contact") }),
        defineField({ name: "andere", title: "Andere (NL)", type: "string", hidden: onlyKey("contact") }),
        defineField({ name: "voorschrift", title: "Voorschrift (NL)", type: "string", hidden: onlyKey("contact") }),
        defineField({ name: "voorschriftHint", title: "Hint bij het voorschrift (NL)", type: "string", hidden: onlyKey("contact") }),
        defineField({ name: "bericht", title: "Bericht (NL)", type: "string", hidden: onlyKey("contact") }),
        defineField({ name: "verstuur", title: "Knop versturen (NL)", type: "string", hidden: onlyKey("contact") }),
        defineField({ name: "bezig", title: "Bezig met versturen (NL)", type: "string", hidden: onlyKey("contact") }),
        defineField({ name: "bedankt", title: "Bedankt (NL)", type: "text", rows: 2, hidden: onlyKey("contact") }),
        defineField({ name: "mislukt", title: "Mislukt (NL)", type: "text", rows: 2, hidden: onlyKey("contact") }),
        defineField({ name: "btw", title: "BTW (NL)", type: "string", hidden: onlyKey("contact") }),
        defineField({ name: "kaart", title: "Kaart (NL)", type: "string", hidden: onlyKey("contact") }),
        defineField({ name: "route", title: "Eerste keer (NL)", type: "string", hidden: onlyKey("contact") }),
        defineField({ name: "fotoOlympia", title: "Beschrijving foto Olympia (NL)", type: "string", hidden: onlyKey("contact") }),
        defineField({ name: "fotoMpc", title: "Beschrijving foto Performance Centre (NL)", type: "string", hidden: onlyKey("contact") }),
        defineField({ name: "welkeEn", title: "Voor welke vestiging? (EN)", type: "string", fieldset: "en", hidden: onlyKey("contact") }),
        defineField({ name: "redenEn", title: "Waarvoor wil je langskomen? (EN)", type: "string", fieldset: "en", hidden: onlyKey("contact") }),
        defineField({ name: "kineEn", title: "Kinesitherapie (EN)", type: "string", fieldset: "en", hidden: onlyKey("contact") }),
        defineField({ name: "trainingEn", title: "Personal training (EN)", type: "string", fieldset: "en", hidden: onlyKey("contact") }),
        defineField({ name: "andereEn", title: "Andere (EN)", type: "string", fieldset: "en", hidden: onlyKey("contact") }),
        defineField({ name: "voorschriftEn", title: "Voorschrift (EN)", type: "string", fieldset: "en", hidden: onlyKey("contact") }),
        defineField({ name: "voorschriftHintEn", title: "Hint bij het voorschrift (EN)", type: "string", fieldset: "en", hidden: onlyKey("contact") }),
        defineField({ name: "berichtEn", title: "Bericht (EN)", type: "string", fieldset: "en", hidden: onlyKey("contact") }),
        defineField({ name: "verstuurEn", title: "Knop versturen (EN)", type: "string", fieldset: "en", hidden: onlyKey("contact") }),
        defineField({ name: "bezigEn", title: "Bezig met versturen (EN)", type: "string", fieldset: "en", hidden: onlyKey("contact") }),
        defineField({ name: "bedanktEn", title: "Bedankt (EN)", type: "text", rows: 2, fieldset: "en", hidden: onlyKey("contact") }),
        defineField({ name: "misluktEn", title: "Mislukt (EN)", type: "text", rows: 2, fieldset: "en", hidden: onlyKey("contact") }),
        defineField({ name: "btwEn", title: "BTW (EN)", type: "string", fieldset: "en", hidden: onlyKey("contact") }),
        defineField({ name: "kaartEn", title: "Kaart (EN)", type: "string", fieldset: "en", hidden: onlyKey("contact") }),
        defineField({ name: "routeEn", title: "Eerste keer (EN)", type: "string", fieldset: "en", hidden: onlyKey("contact") }),
        defineField({ name: "fotoOlympiaEn", title: "Beschrijving foto Olympia (EN)", type: "string", fieldset: "en", hidden: onlyKey("contact") }),
        defineField({ name: "fotoMpcEn", title: "Beschrijving foto Performance Centre (EN)", type: "string", fieldset: "en", hidden: onlyKey("contact") }),
        defineField({ name: "welkomReden", title: "Waarvoor wil je langskomen? (NL)", type: "string", hidden: onlyKey("welkom") }),
        defineField({ name: "welkomKine", title: "Kinesitherapie (NL)", type: "string", hidden: onlyKey("welkom") }),
        defineField({ name: "welkomTraining", title: "Personal training (NL)", type: "string", hidden: onlyKey("welkom") }),
        defineField({ name: "welkomAndere", title: "Andere (NL)", type: "string", hidden: onlyKey("welkom") }),
        defineField({ name: "welkomVoorschrift", title: "Voorschrift (NL)", type: "string", hidden: onlyKey("welkom") }),
        defineField({ name: "welkomHint", title: "Hint (NL)", type: "string", hidden: onlyKey("welkom") }),
        defineField({ name: "welkomBericht", title: "Bericht (NL)", type: "string", hidden: onlyKey("welkom") }),
        defineField({ name: "welkomVerstuur", title: "Knop (NL)", type: "string", hidden: onlyKey("welkom") }),
        defineField({ name: "welkomBezig", title: "Bezig (NL)", type: "string", hidden: onlyKey("welkom") }),
        defineField({ name: "welkomBedankt", title: "Bedankt (NL)", type: "text", rows: 2, hidden: onlyKey("welkom") }),
        defineField({ name: "welkomMislukt", title: "Mislukt (NL)", type: "text", rows: 2, hidden: onlyKey("welkom") }),
        defineField({ name: "welkomRedenEn", title: "Waarvoor wil je langskomen? (EN)", type: "string", fieldset: "en", hidden: onlyKey("welkom") }),
        defineField({ name: "welkomKineEn", title: "Kinesitherapie (EN)", type: "string", fieldset: "en", hidden: onlyKey("welkom") }),
        defineField({ name: "welkomTrainingEn", title: "Personal training (EN)", type: "string", fieldset: "en", hidden: onlyKey("welkom") }),
        defineField({ name: "welkomAndereEn", title: "Andere (EN)", type: "string", fieldset: "en", hidden: onlyKey("welkom") }),
        defineField({ name: "welkomVoorschriftEn", title: "Voorschrift (EN)", type: "string", fieldset: "en", hidden: onlyKey("welkom") }),
        defineField({ name: "welkomHintEn", title: "Hint (EN)", type: "string", fieldset: "en", hidden: onlyKey("welkom") }),
        defineField({ name: "welkomBerichtEn", title: "Bericht (EN)", type: "string", fieldset: "en", hidden: onlyKey("welkom") }),
        defineField({ name: "welkomVerstuurEn", title: "Knop (EN)", type: "string", fieldset: "en", hidden: onlyKey("welkom") }),
        defineField({ name: "welkomBezigEn", title: "Bezig (EN)", type: "string", fieldset: "en", hidden: onlyKey("welkom") }),
        defineField({ name: "welkomBedanktEn", title: "Bedankt (EN)", type: "text", rows: 2, fieldset: "en", hidden: onlyKey("welkom") }),
        defineField({ name: "welkomMisluktEn", title: "Mislukt (EN)", type: "text", rows: 2, fieldset: "en", hidden: onlyKey("welkom") }),
        defineField({ name: "proefles", title: "Boek een proefles (NL)", type: "string", hidden: onlyKey("groepslessen") }),
        defineField({ name: "rooster", title: "Lesrooster (NL)", type: "string", hidden: onlyKey("groepslessen") }),
        defineField({ name: "geenLes", title: "Geen les (NL)", type: "string", hidden: onlyKey("groepslessen") }),
        defineField({ name: "abonnementen", title: "Memberships (NL)", type: "string", hidden: onlyKey("groepslessen") }),
        defineField({ name: "alleTarieven", title: "Alle tarieven (NL)", type: "string", hidden: onlyKey("groepslessen") }),
        defineField({ name: "inschrijven", title: "Inschrijven (NL)", type: "string", hidden: onlyKey("groepslessen") }),
        defineField({ name: "les", title: "Les (NL)", type: "string", hidden: onlyKey("groepslessen") }),
        defineField({ name: "gxBericht", title: "Bericht (NL)", type: "string", hidden: onlyKey("groepslessen") }),
        defineField({ name: "gxVerstuur", title: "Verstuur (NL)", type: "string", hidden: onlyKey("groepslessen") }),
        defineField({ name: "gxBezig", title: "Bezig (NL)", type: "string", hidden: onlyKey("groepslessen") }),
        defineField({ name: "gxGelukt", title: "Gelukt (NL)", type: "string", hidden: onlyKey("groepslessen") }),
        defineField({ name: "gxMislukt", title: "Mislukt (NL)", type: "string", hidden: onlyKey("groepslessen") }),
        defineField({ name: "proeflesEn", title: "Boek een proefles (EN)", type: "string", fieldset: "en", hidden: onlyKey("groepslessen") }),
        defineField({ name: "roosterEn", title: "Lesrooster (EN)", type: "string", fieldset: "en", hidden: onlyKey("groepslessen") }),
        defineField({ name: "geenLesEn", title: "Geen les (EN)", type: "string", fieldset: "en", hidden: onlyKey("groepslessen") }),
        defineField({ name: "abonnementenEn", title: "Memberships (EN)", type: "string", fieldset: "en", hidden: onlyKey("groepslessen") }),
        defineField({ name: "alleTarievenEn", title: "Alle tarieven (EN)", type: "string", fieldset: "en", hidden: onlyKey("groepslessen") }),
        defineField({ name: "inschrijvenEn", title: "Inschrijven (EN)", type: "string", fieldset: "en", hidden: onlyKey("groepslessen") }),
        defineField({ name: "lesEn", title: "Les (EN)", type: "string", fieldset: "en", hidden: onlyKey("groepslessen") }),
        defineField({ name: "gxBerichtEn", title: "Bericht (EN)", type: "string", fieldset: "en", hidden: onlyKey("groepslessen") }),
        defineField({ name: "gxVerstuurEn", title: "Verstuur (EN)", type: "string", fieldset: "en", hidden: onlyKey("groepslessen") }),
        defineField({ name: "gxBezigEn", title: "Bezig (EN)", type: "string", fieldset: "en", hidden: onlyKey("groepslessen") }),
        defineField({ name: "gxGeluktEn", title: "Gelukt (EN)", type: "string", fieldset: "en", hidden: onlyKey("groepslessen") }),
        defineField({ name: "gxMisluktEn", title: "Mislukt (EN)", type: "string", fieldset: "en", hidden: onlyKey("groepslessen") }),
      ],
    }),
    defineField({
      name: "ctaTekst",
      title: "Tekst op de knop onderaan (NL)",
      type: "string",
      group: "blokken",
      hidden: only("mpc-visie"),
    }),
    defineField({ name: "ctaTekstEn", title: "Tekst op de knop onderaan (EN)", type: "string", group: "blokken", fieldset: "en", hidden: only("mpc-visie") }),

    // --- SEO -----------------------------------------------------------
    defineField({
      name: "seoTitle",
      title: "SEO-titel (NL)",
      type: "string",
      group: "seo",
      description: "De titel in het browsertabblad en in Google. Hou het onder 60 tekens.",
      validation: googleTitel,
    }),
    defineField({ name: "seoDescription", title: "SEO-omschrijving (NL)", type: "text", rows: 2, group: "seo", validation: maxTekens(160, GOOGLE_OMSCHRIJVING) }),
    defineField({ name: "seoTitleEn", title: "SEO-titel (EN)", type: "string", group: "seo", fieldset: "en", validation: googleTitel }),
    defineField({ name: "seoDescriptionEn", title: "SEO-omschrijving (EN)", type: "text", rows: 2, group: "seo", fieldset: "en", validation: maxTekens(160, GOOGLE_OMSCHRIJVING) }),
  ],
  preview: {
    select: { key: "key", titel: "titel", media: "foto" },
    prepare({ key, titel, media }) {
      const page = PAGINAS.find((p) => p.key === key);
      return { title: page?.title || key || "Pagina", subtitle: titel, media };
    },
  },
});
